### ISSUE TITLE
Can Binary Ninja solve Obfuscator LLVM’s Bogus Control Flow?

### ISSUE THREAD

**Issue by APlus123** [Vector35/OpaquePredicatePatcher#1]
Generally, we use pattern match to conqure Obfuscator LLVM’s Bogus Control Flow, so can Binary Ninja do this?

**Comment by psifertex** [comment]
Sorry for missing this quite some time ago. In short, this is not in scope for this project, but see: https://rpis.ec/blog/dissection-llvm-obfuscator-p1/
